name: Docker PR Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Docker image
        run: docker build -t countwords-app .

      - name: Run Docker container (optional test)
        run: docker run --rm countwords-app java -jar app.jar
